/**
 * Helpers for testing the lunisolar calendar.
 *
 * Here for the same reasons as {@link ./instants.js}. The lint wants a function
 * capturing nothing from its scope at module scope, the testing style wants
 * nothing at the top level of a test file but imports, and `test/` is excluded
 * from the build so none of it ships.
 *
 * ## Where the testing style bends, and why
 *
 * The house style takes isolation from randomised data. A calendar can only
 * partly oblige. 春节 2026 falls on 17 February whoever asks and however often,
 * and a test that randomised it would assert nothing.
 *
 * So the tests draw on both kinds of input. {@link ./gold-dates.js} holds dates
 * that trace to an authority outside this repository, which is the only defence
 * against a fixture generated by the code it is meant to be testing.
 * {@link randomDates} here supplies randomised Gregorian dates for the
 * properties that hold everywhere, where fixing a date would test one arbitrary
 * case and call it coverage.
 */

import type { Boundary } from "../src/lunar-boundaries.js";

/** A Gregorian date from an ISO string, shortened because tests are full of them. */
export const on = (iso: string): Temporal.PlainDate =>
  Temporal.PlainDate.from(iso);

/**
 * Gregorian dates drawn at random from a range.
 *
 * Seeded from `Math.random`, because a calendar property that holds only for
 * the dates someone thought to write down is not a property. A failure prints
 * the date that caused it, which is enough to reproduce by hand.
 */
export function* randomDates(
  from: number,
  to: number,
  count: number,
): Generator<Temporal.PlainDate> {
  const start = Temporal.PlainDate.from({ year: from, month: 1, day: 1 });
  const span = start.until(
    Temporal.PlainDate.from({ year: to, month: 12, day: 31 }),
  ).days;

  for (let index = 0; index < count; index++) {
    yield start.add({ days: Math.floor(Math.random() * span) });
  }
}

/** Consecutive Gregorian dates, for properties that have to hold on every day. */
export function* everyDayFrom(
  startIso: string,
  count: number,
): Generator<Temporal.PlainDate> {
  let date = on(startIso);
  for (let index = 0; index < count; index++) {
    yield date;
    date = date.add({ days: 1 });
  }
}

/** What the runtime's own Chinese calendar says, for differential testing. */
export function icuChineseDate(date: Temporal.PlainDate): {
  month: number;
  isLeap: boolean;
  day: number;
} {
  const chinese = date.withCalendar("chinese");
  const code = chinese.monthCode;
  return {
    month: Number(code.replaceAll(/[ML]/gu, "")),
    isLeap: code.endsWith("L"),
    day: chinese.day,
  };
}

/**
 * A month boundary carrying a chosen solar-longitude sector.
 *
 * For exercising the leap rule on spans the astronomy does not produce. The
 * instant and date are arbitrary, because only the sector decides whether a
 * month contains a 中气.
 */
export function boundaryAt(sector: number): Boundary {
  return {
    instant: Temporal.Instant.from("2026-01-01T00:00:00Z"),
    date: on("2026-01-01"),
    sector,
  };
}

/** A run of `count` months whose boundaries each advance one sector. */
export function everySectorAdvancing(
  count: number,
): readonly (readonly [Boundary, Boundary])[] {
  return Array.from(
    { length: count },
    (_, index) => [boundaryAt(index), boundaryAt(index + 1)] as const,
  );
}
