/**
 * Dates whose lunisolar value is published somewhere other than this
 * repository.
 *
 * Every entry has to trace to an outside authority. A fixture generated by
 * nongli and then used to test nongli tests that nongli is stable, which is a
 * much weaker claim than the one these are here to make.
 *
 * Kept apart from the helpers in {@link ./calendar.js} because this is data and
 * those are code, and the two grow at different rates.
 */

import type { LunisolarDate } from "../src/lunisolar.js";

/** A published date, and where the publication came from. */
export interface GoldDate {
  readonly iso: string;
  readonly expected: LunisolarDate;
  readonly source: string;
}

export const GOLD: readonly GoldDate[] = [
  {
    iso: "2026-02-17",
    expected: { year: 2026, month: 1, isLeap: false, day: 1 },
    source: "春节 2026, published widely",
  },
  {
    iso: "2024-02-10",
    expected: { year: 2024, month: 1, isLeap: false, day: 1 },
    source: "春节 2024",
  },
  {
    iso: "2033-12-22",
    expected: { year: 2033, month: 11, isLeap: true, day: 1 },
    source: "闰十一月 2033, the case naive implementations get wrong",
  },
  {
    iso: "2020-01-25",
    expected: { year: 2020, month: 1, isLeap: false, day: 1 },
    source: "春节 2020",
  },
  {
    iso: "2023-03-22",
    expected: { year: 2023, month: 2, isLeap: true, day: 1 },
    source: "闰二月 2023",
  },
];
